### ISSUE TITLE
support for VirtualBox

### ISSUE THREAD

**Issue by arozehnal** [vaniacer/sshto#10]
Is it possible to use sshto from a Virtualbox client installation?
After running sshto, only the contents of the current directory is printed.

uname -a 
Linux roku 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

hostnamectl
 Static hostname: roku
       Icon name: computer-vm
         Chassis: vm
      Machine ID: 6c4529d835e546e4b96a3758071e0488
         Boot ID: 1fb57395bda747cf8062c1dc6a0a3763
  Virtualization: oracle
Operating System: Ubuntu 21.10                    
          Kernel: Linux 5.13.0-37-generic
    Architecture: x86-64
 Hardware Vendor: innotek GmbH
  Hardware Model: VirtualBox

locale
Linux roku 5.13.0-37-generic #42-Ubuntu SMP Tue Mar 15 14:34:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LANG=cs_CZ.UTF-8
LANGUAGE=cs:en_US
LC_CTYPE="cs_CZ.UTF-8"
LC_NUMERIC="cs_CZ.UTF-8"
LC_TIME="cs_CZ.UTF-8"
LC_COLLATE="cs_CZ.UTF-8"
LC_MONETARY="cs_CZ.UTF-8"
LC_MESSAGES="cs_CZ.UTF-8"
LC_PAPER="cs_CZ.UTF-8"
LC_NAME="cs_CZ.UTF-8"
LC_ADDRESS="cs_CZ.UTF-8"
LC_TELEPHONE="cs_CZ.UTF-8"
LC_MEASUREMENT="cs_CZ.UTF-8"
LC_IDENTIFICATION="cs_CZ.UTF-8"
LC_ALL=

dialog --version
Version: 1.3-20201126

**Comment by arozehnal** [comment]
I tried to add tracing with 'set -x'. Here is the output:

++ uname -s
+ [[ Linux == \D\a\r\w\i\n ]]
+ ls --color=auto

**Comment by arozehnal** [comment]
The problem was not caused by Virtualbox or sshto, but by an awk error - see -> [https://bugs.launchpad.net/ubuntu/+source/bash-completion/+bug/1845529](url)
After installation gawk sshto works finee

**Comment by vaniacer** [comment]
Cool, thanks!)
