### ISSUE TITLE
Dialog error message is `Expected at least 20 tokens` since Awk changes

### ISSUE THREAD

**Issue by zeroheure** [vaniacer/sshto#11]
Dialog doesn't like the new awk list creation (commit [68ad4dd](https://github.com/vaniacer/sshto/commit/68ad4dd3c1509bcffc952883f01c9c99fdfbf31f)). Specialy this line create problem: 
` --menu "Select host to connect to. $USERNOTE" 0 0 0 "${list[@]}")`

Dialog error message is 
`Expected at least 20 tokens for --men, have 4.` 
followed by 
`ESC[0mESC[?25hESC[HESC[2JESC[3J` 
followed by current directory content.

Unrelated, but additonaly only few lines of the output can be seen, and the output is not browsable (terminal window looks locked at current screen).

It is a known issue with Dialog, very similar to [this old error on slackware](https://www.linuxquestions.org/questions/slackware-14/slackpkg-error-expected-at-least-7-tokens-for-checklist-have-4-a-4175550920/). Browse at the bottom for explanation.

**Comment by vaniacer** [comment]
Is this https://github.com/vaniacer/sshto/commit/16d203e5d78e9e45b243600c6d19a44ed08e2c5d fixed the issue?

**Comment by zeroheure** [comment]
Yes ! thank you !
