### ISSUE TITLE
Failed run on ubuntu 20

### ISSUE THREAD

**Issue by IvanKalashnikov** [vaniacer/sshto#12]
Hello, failed run on ubuntu

```
softj@softjpc:~$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
softj@softjpc:~$ uname -r
5.13.0-39-generic
```

I get this error

```
awk line 17 function gensub never defined
```

after install **gawk** it was fixed for me

```
sudo apt install gawk
```

may be should add this to readme or checking in sshto script?

**Comment by vaniacer** [comment]
Fixed by https://github.com/vaniacer/sshto/commit/16d203e5d78e9e45b243600c6d19a44ed08e2c5d
Thanks!
