### ISSUE TITLE
Failed run permission problem ?

### ISSUE THREAD

**Issue by iakrylov** [vaniacer/sshto#13]
`awk: cmd. line:14: fatal: cannot open file '/home/username/.ssh/config*[!~]' for reading: no such file of directory`

Permission on config
```
stat -c "%a %n" /home/username/.ssh/config
644 /home/username/.ssh/config
```

`username@debian:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye`

**Comment by vaniacer** [comment]
Fixed by https://github.com/vaniacer/sshto/commit/16d203e5d78e9e45b243600c6d19a44ed08e2c5d
Thanks!
