### ISSUE TITLE
Declare -A invalid option

### ISSUE THREAD

**Issue by Land-Maze** [vaniacer/sshto#16]
There's some issue with declare option -A

Device: MacBook M1
Os: 12.3

https://user-images.githubusercontent.com/61432929/196116549-400cab48-d10d-4b03-bfd6-3d591fad836c.mov

<img width="772" alt="Screenshot 2022-10-17 at 10 38 40 AM" src="https://user-images.githubusercontent.com/61432929/196117029-0e4f0a0f-586d-4649-a120-07d39712a9c5.png">

**Comment by vaniacer** [comment]
Bash version is too low. Have to be 4+
