### ISSUE TITLE
After closing the app it lists entire current working directory

### ISSUE THREAD

**Issue by Real-Gecko** [vaniacer/sshto#17]
Just watch the video, happens when closing with hitting `Esc` and when selecting `Exit` menu option.

https://user-images.githubusercontent.com/2231969/196354105-156f9158-d611-4ad1-b803-c60d2eed9b04.mp4

**Comment by vaniacer** [comment]
Yes it's by design:
```
...
#------------------------{ Exit function }------------------------------------------------------------------------------
bye(){ printf "\n$DEF$CON"; clear; [[ $(uname -s) == "Darwin" ]] && ls -G || ls --color=auto; exit 0; }; trap bye INT
...
```

**Comment by Real-Gecko** [comment]
Sorry, but what's the point of this?

**Comment by vaniacer** [comment]
It's quite convenient for me to have list of files(dirs) in current folder when I'm working in console.

**Comment by vaniacer** [comment]
Done https://github.com/vaniacer/sshto/commit/6e58c01cfa9a996a2cc0647ec0cf4615c20217db

**Comment by Real-Gecko** [comment]
Thank you!
