### ISSUE TITLE
Doesn't work with possible uses of Include keyword

### ISSUE THREAD

**Issue by kapsh** [vaniacer/sshto#2]
`sshto` doesn't use configuration files included in `.ssh/config`. 

Example setup: 
```
❯ cat ~/.ssh/config
Include ananas/config
Include github/config
# blah-blah

/tmp
❯ cat ~/.ssh/github/config
# vim: filetype=sshconfig:

Host github.com
    User git
    IdentityFile ~/.ssh/github/kapsh_github
```

When all hosts (except default options for `Host *`) are configured in this way, sshto just shows nothing and exits.

**Comment by kapsh** [comment]
I saw the readme, but (looking at code) `sshto` does not read `Include` in fact but only lists `.ssh/config*`.

**Comment by vaniacer** [comment]
Exactly, that is why included config files have to be in ~/.ssh dir, and start from 'config', example:
Include config_*
