### ISSUE TITLE
Add MacOS Compatibility

### ISSUE THREAD

**Issue by mattdonders** [vaniacer/sshto#3]
Just found this script (exactly what I've been looking for) & running this on MacOS and I found the following two issues that I can fix via PR if you'd like.

1. If `dialog` not installed on the system, the script recommends I run the command `sudo apt-get install -y dialog` where I use `brew install dialog` on my MacOS system.

2. When you exit the dialog, you get the following error due to the `ls --color=auto` command.
```
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

Let me know if you'd like me to code up these fixes using `uname -s` detection of a MacOS system.

Thanks!

**Comment by vaniacer** [comment]
Hi, yes i'd like to!
